name: Parallal Test
on: push
jobs:
  addToCartPage-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run addToCartPage:run

      - name: Test Report-Add To Card Page
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: Mochaawsome HTML Report-Add To Card Page
            path: cypress/reports    
    
  loginPage-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run loginPage:run
    
      - name: Test Report-Login Page
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochaawsome HTML Report-login page
          path: cypress/reports 

